name: qwen-lora
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - expat=2.7.3=h7354ed3_4
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - accelerate==1.9.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - av==16.1.0
      - bitsandbytes==0.49.1
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - coloredlogs==15.0.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==4.0.0
      - deepspeed==0.17.4
      - diffusers==0.37.0.dev0
      - dill==0.3.8
      - einops==0.8.0
      - exceptiongroup==1.3.1
      - filelock==3.20.3
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.3.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - h11==0.16.0
      - hf-xet==1.2.0
      - hjson==3.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.34.3
      - humanfriendly==10.0
      - idna==3.11
      - importlib-metadata==8.7.1
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - loguru==0.7.3
      - markupsafe==3.0.3
      - matplotlib==3.10.5
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - multiprocess==0.70.16
      - networkx==3.4.2
      - ninja==1.13.0
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - onnxruntime==1.22.1
      - opencv-python==4.12.0.88
      - optimum-quanto==0.2.7
      - packaging==26.0
      - pandas==2.3.3
      - peft==0.17.0
      - pillow==12.1.0
      - platformdirs==4.5.1
      - propcache==0.4.1
      - protobuf==6.33.4
      - psutil==7.2.1
      - py-cpuinfo==9.0.0
      - pyarrow==23.0.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - qwen-vl-utils==0.0.11
      - regex==2026.1.15
      - requests==2.32.5
      - safetensors==0.7.0
      - sentencepiece==0.2.0
      - sentry-sdk==2.50.0
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.14.0
      - timm==1.0.19
      - tokenizers==0.21.4
      - torch==2.7.1
      - torchvision==0.22.1
      - tqdm==4.67.1
      - transformers==4.55.0
      - triton==3.3.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.3
      - wandb==0.24.0
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /home/kuan/miniconda3/envs/qwen-lora
